Replace rbenv with st2 in executables

diff --git a/libexec/rbenv b/libexec/rbenv
--- a/libexec/rbenv
+++ b/libexec/rbenv
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$ST2_DEBUG" ] && set -x
 
 resolve_link() {
   $(type -p greadlink readlink | head -1) "$1"
@@ -20,39 +20,39 @@ abs_dirname() {
   cd "$cwd"
 }
 
-if [ -z "${RBENV_ROOT}" ]; then
-  RBENV_ROOT="${HOME}/.rbenv"
+if [ -z "${ST2_ROOT}" ]; then
+  ST2_ROOT="${HOME}/.st2"
 else
-  RBENV_ROOT="${RBENV_ROOT%/}"
+  ST2_ROOT="${ST2_ROOT%/}"
 fi
-export RBENV_ROOT
+export ST2_ROOT
 
-if [ -z "${RBENV_DIR}" ]; then
-  RBENV_DIR="$(pwd)"
+if [ -z "${ST2_DIR}" ]; then
+  ST2_DIR="$(pwd)"
 else
-  cd "$RBENV_DIR" 2>/dev/null || {
-    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
+  cd "$ST2_DIR" 2>/dev/null || {
+    echo "st2: cannot change working directory to \`$ST2_DIR'"
     exit 1
   } >&2
-  RBENV_DIR="$(pwd)"
+  ST2_DIR="$(pwd)"
   cd "$OLDPWD"
 fi
-export RBENV_DIR
+export ST2_DIR
 
 
 shopt -s nullglob
 
 bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
+for plugin_bin in "${ST2_ROOT}/plugins/"*/bin; do
   bin_path="${bin_path}:${plugin_bin}"
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
+hook_path="${ST2_HOOK_PATH}:${ST2_ROOT}/st2.d:/usr/local/etc/st2.d:/etc/st2.d:/usr/lib/st2/hooks"
+for plugin_hook in "${ST2_ROOT}/plugins/"*/etc/st2.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
-export RBENV_HOOK_PATH="$hook_path"
+export ST2_HOOK_PATH="$hook_path"
 
 shopt -u nullglob
 
@@ -60,15 +60,15 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "$(rbenv---version)\n$(rbenv-help)" >&2
+  echo -e "$(st2-version)\n$(st2-help)" >&2
   ;;
 "-v" )
-  exec rbenv---version
+  exec st2-version
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "st2-$command" || true)"
   if [ -z "$command_path" ]; then
-    echo "rbenv: no such command \`$command'" >&2
+    echo "st2: no such command \`$command'" >&2
     exit 1
   fi
 
